<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/12/11 13:29:06

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=idea',
  'username' => 'admin',
  'password' => 'chachacha',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
